# Generated by Django 6.0.6 on 2026-06-12 21:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Employee ID')),
                ('department', models.CharField(default='General', max_length=100)),
                ('designation', models.CharField(default='Associate', max_length=100)),
                ('date_of_joining', models.DateField(default=django.utils.timezone.now)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SICK', 'Sick Leave'), ('ANNUAL', 'Annual Leave'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave'), ('UNPAID', 'Unpaid Leave'), ('OTHER', 'Other Request')], default='ANNUAL', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='zenhr.employeeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CALCULATING', 'Calculating'), ('PROCESSING', 'Processing'), ('PAID', 'Paid')], default='OPEN', max_length=20)),
            ],
            options={
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('latitude_in', models.FloatField(blank=True, null=True)),
                ('longitude_in', models.FloatField(blank=True, null=True)),
                ('latitude_out', models.FloatField(blank=True, null=True)),
                ('longitude_out', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('ON_LEAVE', 'On Leave')], default='PRESENT', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='zenhr.employeeprofile')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('social_security', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_withheld', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('loan_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('released', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='zenhr.employeeprofile')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='zenhr.payrollperiod')),
            ],
            options={
                'unique_together': {('employee', 'payroll_period')},
            },
        ),
    ]
